# Generated by Django 4.2.2 on 2023-06-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('superblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigin',
            name='groups',
            field=models.ManyToManyField(related_name='sigin_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='sigin',
            name='user_permissions',
            field=models.ManyToManyField(related_name='sigin_user_permissions', to='auth.permission'),
        ),
    ]
