# Generated by Django 4.2.2 on 2023-06-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superblogapp', '0002_sigin_groups_sigin_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sigin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='sigin',
            name='user_permissions',
        ),
    ]
